### ISSUE TITLE
Support of x-callback-url

### ISSUE THREAD

**Issue by Ustice** [neerajbaid/goo.gl#1]
## Overview

Far from a stand-alone utility, goo.gl could work with other apps by supporting [x-callback-urls](http://x-callback-url.com/specifications).
## Suggested URL Schema

The url should be in the form of

```
googl://x-callback-ul/shorten?[x-callback parameters]&[action parameters]
```

In addition to the x-callback-url schema, goo.gl should support the following action parameters:
- **longurl=[URL-encoded URL]**: take a url, and process that through goo.gl, and copy the output.
- **twitter=yes**: Invoke the Share with Twitter button.
- **facebook=yes**: Invoke the Share with Facebook button.
- **messages=yes**: Invoke the Share with Messages button.
- **email=yes**: Invoke the Share with Mail button.
- **autosend=yes**: automatically sends shared link to either Twitter or Facebook. Ignored in the case of messages and email.
## Use Cases

For instance I can see a use-case where in Launch Center Pro, a user could create an action that will allow them to select a file in the their dropbox, get a public URL for that file, have it sent to goo.gl to be shortened, returned, and then allow them to send it to some other service.

Also a user could create a bookmarklet to send the current url to goo.gl, have it shortened, and then return to the browser.

Potential use-cases are unlimited.
## References
1. [x-callback-url specifications](http://x-callback-url.com/specifications)
2. [Writing Custom URL Schemes in Objective C](http://www.idev101.com/code/Objective-C/custom_url_schemes.html)

**Comment by neerajbaid** [comment]
Thanks for this. I'm investigating.

**Comment by neerajbaid** [comment]
I believe the API is simple enough where any serious integrator could simply directly hit Google's API.
